services:
    postgres:
        container_name: postgres
        image: postgres:16-alpine
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: keycloak
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: password
    keycloak:
        container_name: keycloak
        image: quay.io/keycloak/keycloak:22.0
        environment:
            # keycloak settings
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
            KEYCLOAK_LOGLEVEL: INFO
            ROOT_LOGLEVEL: INFO
            # database
            KC_DB: postgres
            KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
            KC_DB_USERNAME: keycloak
            KC_DB_PASSWORD: password
        ports:
            - 8080:8080
        depends_on:
            - postgres
        command: start-dev
    ui:
        container_name: ui
        build:
            context: ui
            dockerfile: Dockerfile.dev
        user: 1000:1000
        stdin_open: true
        tty: true
        ports:
            - "8000:3000"
        volumes:
            - ./ui/source:/home/node
            - ./.env:/home/node/.env
        command: sh -c "yarn install && yarn run dev"
        env_file:
            - .env
    service-a:
        container_name: service-a
        build:
            context: service-a
            dockerfile: Dockerfile.dev
        user: 1000:1000
        stdin_open: true
        tty: true
        ports:
            - "8001:3000"
        volumes:
            - ./service-a/source:/home/node
        command: sh -c "yarn install && yarn start:dev"
        env_file:
            - .env
    service-b:
        container_name: service-b
        build:
            context: service-b
            dockerfile: Dockerfile.dev
        user: 1000:1000
        stdin_open: true
        tty: true
        ports:
            - "8002:3000"
        volumes:
            - ./service-b/source:/home/node
        command: sh -c "yarn install && yarn start:dev"
        env_file:
            - .env

volumes:
    postgres:
        driver: local
